### ISSUE TITLE
Build fails on eXist 5

### ISSUE THREAD

**Issue by joewiz** [ljo/exist-stanford-corenlp#3]
A fresh clone fails to build on eXist 5.0.0-SNAPSHOT (develop).

```bash
$ ant
Buildfile: /Users/joe/workspace/exist-stanford-corenlp/build.xml

prepare:

compile:
    [javac] /Users/joe/workspace/exist-stanford-corenlp/build.xml:56: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 2 source files to /Users/joe/workspace/exist-stanford-corenlp/build/classes
    [javac] /Users/joe/workspace/exist-stanford-corenlp/java/src/org/exist/xquery/corenlp/util/DefaultBinaryValueManager.java:34: error: DefaultBinaryValueManager is not abstract and does not override abstract method runCleanupTasks(Predicate<Object>) in BinaryValueManager
    [javac] public class DefaultBinaryValueManager implements BinaryValueManager {
    [javac]        ^
    [javac] 1 error

BUILD FAILED
/Users/joe/workspace/exist-stanford-corenlp/build.xml:56: Compile failed; see the compiler error output for details.

Total time: 1 second
```
